name: Build EXE

on:
  push:
    branches:
      - recode

jobs:
  build:
    name: Build and Upload Exe
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v4.0.2 # https://github.com/actions/cache/releases
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build JAR and EXE with Gradle
        run: ./gradlew build createExe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: ChessApp
          path: build/launch4j/*.exe